
------------------------------------------
--		 	Flyff Earthquake v4.0		--
--		   PREMIUM_SHOP_TBL.SQL			--
--		   Created by Treachery.		--
------------------------------------------

USE [CHARACTER_01_DBF]
GO
/****** Object:  Table [dbo].[PREMIUM_SHOP_TBL]    Script Date: 06/02/2010 15:05:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PREMIUM_SHOP_TBL](
	[id] [int] NOT NULL,
	[itemid] [int] NOT NULL,
	[name] [varchar](75) COLLATE Korean_Wansung_CI_AS NOT NULL,
	[desc] [text] COLLATE Korean_Wansung_CI_AS NOT NULL,
	[itemcount] [int] NOT NULL DEFAULT ((1)),
	[price] [int] NOT NULL,
	[price_sale] [int] NULL DEFAULT (NULL),
	[category] [varchar](1) COLLATE Korean_Wansung_CI_AS NOT NULL,
	[purchases] [int] NOT NULL DEFAULT ((0)),
	[image] [varchar](4) COLLATE Korean_Wansung_CI_AS NOT NULL DEFAULT ('.png'),
	[isbundle] [int] NOT NULL DEFAULT ((0)),
	[forsale] [int] NOT NULL DEFAULT ((1)),
	[item1_id] [int] NULL DEFAULT (NULL),
	[item1_name] [varchar](75) COLLATE Korean_Wansung_CI_AS NULL DEFAULT (NULL),
	[item1_count] [int] NULL DEFAULT (NULL),
	[item2_id] [int] NULL DEFAULT (NULL),
	[item2_name] [varchar](75) COLLATE Korean_Wansung_CI_AS NULL DEFAULT (NULL),
	[item2_count] [int] NULL DEFAULT (NULL),
	[item3_id] [int] NULL DEFAULT (NULL),
	[item3_name] [varchar](75) COLLATE Korean_Wansung_CI_AS NULL DEFAULT (NULL),
	[item3_count] [int] NULL DEFAULT (NULL),
	[item4_id] [int] NULL DEFAULT (NULL),
	[item4_name] [varchar](75) COLLATE Korean_Wansung_CI_AS NULL DEFAULT (NULL),
	[item4_count] [int] NULL DEFAULT (NULL),
 CONSTRAINT [PK_PREMIUM_SHOP_TBL] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('1', '6319', 'Cupid Wings', 'Use this item to give your character glowing Cupid Wings for a limited time! ', '10', '3', NULL, 'Y', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('2', '76', 'Police Club', 'Police Club', '1', '3', NULL, 'Y', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('3', '26005', 'Baby Aibatt Trans', 'Magical ball which has the mysterious power to transfer into Baby Aibatt for 5 min.', '10', '1', NULL, 'Y', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('4', '26002', 'Aibatt Trans', 'Magical ball which has the mysterious power to transfer into Aibatt for 5 min.', '10', '1', NULL, 'Y', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('5', '6320', 'Heart Stone', 'A decorative weapon which is in the shape of a heart.', '1', '2', NULL, 'Y', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('6', '26217', 'Friendship B', 'This item allows you to summon another player to your location with no casting time.', '5', '4', NULL, 'X', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('7', '26201', 'Friendship A', 'This item allows you to summon another player to your location. Casting Time - 30 seconds.', '5', '2', NULL, 'X', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('8', '26454', 'Silver Battery', '10 Day battery for the Collector. (Expires 10 Days after activation even if not being used.)', '1', '4', NULL, 'X', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('9', '26455', 'Gold Battery', '20 Day battery for the Collector. (Expires 20 Days after activation even if not being used.)', '1', '7', NULL, 'X', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('10', '26695', 'Modern Style Bed (7 Days)', 'This modern style bed increases your Strength by +5 when used to decorate your house. Expires after 7 days.', '1', '2', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('11', '26696', 'Modern Drawer (7 Days)', 'This modern style drawer increases your Dexterity by +5 when used to decorate your house. Expires after 7 days.', '1', '2', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('12', '26697', 'Modern Dresser (7 Days)', 'This modern style dresser increases your Intellect by +5 when used to decorate your house. Expires after 7 days.', '1', '2', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('13', '26698', 'Modern Sofa (7 Days)', 'This modern style sofa increases your Defense Power by +6 and your Stamina by +5 when used to decorate your house. Expires after 7 days.', '1', '3', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('14', '26699', 'Modern Table (7 Days)', 'This modern style table increases your Attack Power by +200 when used to decorate your house. Expires after 7 days.', '1', '3', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('15', '26700', 'Modern Wardrobe (7 Days)', 'This modern style wardrobe increases your Defense Power by +150 when used to decorate your house. Expires after 7 days.', '1', '3', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('16', '26741', 'Granite Flooring (7 Days)', 'Granite-style Flooring that increases your Run Speed by 10% when used to decorate your house. Expires after 7 days.', '1', '2', NULL, 'W', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('17', '26743', 'Shabby-Chic Wallpaper (7 Days)', 'Shabby-Chic Wallpaper that increases your Attack Speed by 10% and reduces your Casting Time by 5% when used to decorate your house. Expires after 7 days.', '1', '3', NULL, 'W', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('18', '20198', 'Elegant Guild House Bookshelf', 'An elegant bookshelf for a guild house. Provides +5 INT to all guild members when installed. Lasts 7 days. ', '1', '5', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('19', '20199', 'Elegant Guild House End Table', 'An elegant end table for a guild house. Provides +5 DEX to all guild members when installed. Lasts 7 days. ', '1', '5', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('20', '20200', 'Elegant Guild House Chair', 'An elegant chair for a guild house. Provides +2 STR to all guild members when installed. Lasts 7 days.', '1', '5', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('21', '20201', 'Elegant Guild House Table', 'An elegant table for a guild house. Provides +5% Block Rate to all guild members when installed. Lasts 7 days. ', '1', '5', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('22', '20197', 'Elegant Guild House Sofa', 'An elegant sofa for a guild house. Provides +5 STA to all guild members when installed. Lasts 7 days. ', '1', '4', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('23', '20202', 'Elegant Guild House Carpet', 'Elegant carpeting for a guild house. Provides +10% Run Speed to all guild members when installed. Lasts 7 days. ', '1', '4', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('24', '20203', 'Elegant Guild House Wallpaper', 'Elegant wallpaper for a guild house. Provides 10% Attack Speed and decreases Casting Speed by 5% to all guild members when installed. Lasts 7 days. ', '1', '4', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('25', '26797', 'Modern Style Furniture Package (7 days)', 'The Full Modern Style Furniture Set. Each item lasts 7 days.', '1', '15', '12', 'W', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('26', '20196', 'Bubble''s EXP Crystal', 'This dazzling crystal allows the use of the Bubble Time Guage which grants bonus EXP when placed in a Guild House. This Crystal lasts 7 days. ', '1', '12', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('27', '20124', 'Summon: Apprentice Teleporter', 'This ticket allows you to summon an Apprentice Teleporter for your Guild House. The Apprentice Teleporter allows you to teleport to specific locations directly from your Guild House. ', '1', '3', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('28', '20185', 'Summon: Master Teleporter', 'This ticket allows you to summon a Master Teleporter for your Guild House. The Master Teleporter allows you to teleport to specific locations directly from your Guild House. Allows travel to more places than the Apprentice Teleporter. ', '1', '5', NULL, 'W', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('29', '15220', 'Scroll of Custody', 'Summons an Banker Pang for three minutes.', '10', '3', NULL, 'K', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('30', '4422', 'Shiny Glasses', 'Sunglass(FP+100, MP+100)', '1', '14', NULL, 'U', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('31', '4444', 'Mini Glasses (White)', 'These Fashionable White Mini Glasses increase your Focus Points (FP) and Health Points (HP) by +100.', '1', '12', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('32', '4445', 'Mini Glasses (Red)', 'Fashionable Blue Mini Glasses that increase your Magic Points (MP) and Health Points (HP) by +100.', '1', '12', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('33', '4446', 'Mini Glasses (Blue)', 'Fashionable Blue Mini Glasses that increase your Magic Points (MP) and Focus Points (FP) by +100.', '1', '12', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('34', '4440', 'Glasses (Yellow)', 'Stylish Yellow Glasses that increase your Magic Points (MP) and Focus Points (FP) by +150.', '1', '18', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('35', '4442', 'Glasses (Purple)', 'Stylish Purple Glasses that increase your Health Points (HP) and Magic Points (MP) by +150.', '1', '18', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('36', '4439', 'Glasses (Red)', 'Stylish Red Glasses that increase your Health Points (HP and Focus Points (FP) by +150.', '1', '18', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('37', '4436', 'Sunglasses (White)', 'Slick White Sunglasses that increase your Magic Points (MP) and Focus Points (FP) by +100.', '1', '12', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('38', '4437', 'Sunglasses (Red)', 'Slick Red Sunglasses that increase your Health Points (HP) and Magic Points (MP) by +100.', '1', '12', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('39', '4438', 'Sunglasses (Blue)', 'Slick Blue Sunglasses that increase your Focus Points (FP) and Health Points (HP) by +100.', '1', '12', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('40', '4433', 'Fashion Sunglasses (Orange)', 'Stunning Orange Fashion Sunglasses that increase your Magic Points (MP) and Focus Points (FP) by +150.', '1', '18', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('41', '4434', 'Fashion Sunglasses (Green)', 'Stunning Green Fashion Sunglasses that increase your Focus Points (FP) and Health Points (HP) by +150.', '1', '18', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('42', '4432', 'Fashion Sunglasses (Red)', 'Stunning Red Fashion Sunglasses that increase your Health Points (HP) and Magic Points (MP) by +150.', '1', '18', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('43', '10273', 'Cloak of Strong', 'The Cloak of Strong increases your Strength (STR) by +8.', '1', '10', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('44', '10274', 'Cloak of Accord', 'The Cloak of Accord increases your Stamina (STA) by +4 and your Intelligence (INT) by +4.', '1', '10', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('45', '10481', 'Cloak of Quick', 'The Cloak of Quick increases your Strength (STR) by +4 and your Dexterity (DEX) by +4.', '1', '10', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('46', '10275', 'Cloak of Wisdom', 'The Cloak of Wisdom increases your Intelligence (INT) by +8.', '1', '10', NULL, 'U', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('47', '5105', 'Tiger Board', 'Fast Flying Tiger Board with a Max Speed of 218km/h.', '1', '10', NULL, 'R', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('48', '5005', 'Hera Hoverbike (Black)', 'Black version of Hoverbike. (Max Speed: 233km/h). ', '1', '15', NULL, 'R', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('49', '5823', 'Air Shark Board', 'The Air Shark Board is one of the fastest boards in Madrigal! With a top speed of 254 km/h, this board SCREAMS!', '1', '18', NULL, 'R', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('50', '5821', 'Angelic Wings', 'Illustrating beauty and brilliance, these are truly the Wings of an Angel.\r\nMaximum Speed: 269 km/h.', '1', '24', NULL, 'R', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('51', '5822', 'Wings of the Divine Prophet', 'The Wings of the Divine Prophet are the ultimate display of grace, radiance, and authority.\r\nMaximum Speed: 276 km/h.', '1', '30', NULL, 'R', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('52', '26892', 'Precious Bead of Malice', 'Increases all damage done against masquerpets by 3% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever.', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('53', '26891', 'Precious Bead of Soul Reaving', 'Recovers 70 HP when the target masquerpets is defeated. Lasts 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('54', '26890', 'Precious Bead of Fortitude', 'Increases your Maximum Health Points (Max HP) by 10% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('55', '26889', 'Precious Bead of Evasion', 'Increases your Parry Rate by 5% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('56', '26888', 'Precious Bead of the Sorceror', 'Increases your Magic Attack by +60 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever.', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('57', '26887', 'Precious Bead of the Protector', 'Increases your Defense Power by +60 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('58', '26886', 'Precious Bead of Power', 'Increases your Attack Power by +60 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('59', '26885', 'Precious Bead of Swiftness', 'Increases your Attack Speed by 11% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('60', '26884', 'Precious Bead of Accuracy', 'Increases your Chance to Hit by 7% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('61', '26883', 'Precious Bead of the Winds', 'Increases your Run Speed by 17% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('62', '26882', 'Precious Bead of Profuse Bleeding', 'Increases Additional Damage on Critical Hits by 7% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('63', '26881', 'Precious Bead of Recklessness', 'Increases Additional Damage on Critical Chance by 7% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('64', '26880', 'Precious Bead of the Ardent Defender', 'Increases your chance to block ranged attacks by 7% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('65', '26879', 'Precious Bead of the Steadfast Defender', 'Increases your chance to block melee attacks by 7% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('66', '26878', 'Precious Bead of Focused Power', 'Increases your Magical Power by +30, and Decreases your Casting Time by 4% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('67', '26877', 'Precious Bead of Clarity', 'Decreases your Casting Time by 7% for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('68', '26876', 'Precious Bead of Relentless Power', 'Increases Additional Damage done by +150 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('69', '26875', 'Precious Bead of the Lion', 'Increases your Stamina (STA) by +7 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('70', '26874', 'Precious Bead of the Fox', 'Increases your Intelligence (INT) by +7 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('71', '26873', 'Precious Bead of the Rabbit', 'Increases your Dexterity (DEX) by +7 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('72', '26872', 'Precious Bead of the Tiger', 'Increases your Strength (STR) by +7 for 3 days when placed in a Buff Pets Bead Slot. Double click the bead to remove it from a Bead Slot. Warning: Once removed, the bead is lost forever. ', '1', '1', NULL, 'Q', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('73', '26522', 'Scroll of Pet Revival (S Class)', 'Revives a dead S Class pet. ', '1', '20', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('74', '26523', 'Scroll of Pet Revival (A Class)', 'Revives a dead A Class pet. ', '1', '15', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('75', '26524', 'Scroll of Pet Revival (B Class)', 'Revives a dead B Class pet. ', '1', '10', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('76', '20039', 'Scroll of Pet Name Change (Raised Pets)', 'This scroll allows the user to change the name of a raised pet.', '1', '3', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('77', '21036', 'Egg Hatcher', 'This special Egg Hatcher allows you to turn an egg into a D Class pet instantly! Simply use the Egg Hatcher and return to the Pet Tamer in any city.', '1', '3', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('78', '21033', 'Pet Medicine (B)', 'Your raised pets health will not decrease for 10 minutes while under the effects of this item.\r\n\r\nAdditionally, your pets growth rate (EXP Gain) will increase by 50% for the duration of the effect.', '10', '2', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('79', '21032', 'Pet Medicine (A)', 'Your raised pets health will not decrease for 10 minutes while under the effects of this item.', '10', '1', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('80', '26531', 'Feed Bag (6 hrs)', 'Feeds your pet automatically with Pet Feed from your Inventory. The Pet Feeb Bag will last for 6 hours from activation.', '1', '4', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('81', '26573', 'Feed for (S) Class Pet', 'Automatic Pet feed for 15 days, only for (S) Class pet. It is not available for A,B,C, or D Classes.', '1', '3', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('82', '21034', 'Pet Energy', 'Use this item on your Raised Pet to give it anywhere from 1 to 5 lives at random.\r\n\r\nPlease note: The Pet MUST still be alive in orer for it to work.', '1', '6', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('83', '21030', 'Blessing of the Pet Tamer', 'Cancel the present class and go back to the previous class with 99.99% EXP. You can talk with the Pet Tamer, upgrade the pet class, and receive a random stat again.(The possible pet classes are: C/B/A/S).', '1', '5', NULL, 'P', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('84', '20025', 'Scroll of Pet Reversion (Raised Pets)', 'Removes the awakened traits of a C/B/A/S class pet.\r\nAfter the awakening is removed, you can then apply another another awakening.', '1', '2', NULL, 'E', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('85', '26614', 'Scroll of Pet Blessing (Pick-Up Pets)', 'Places a blessing on a Pick-up Pet, revealing hidden traits.\r\nTo replace the hidden trait with a new one, simply use another Scroll of Pet Blessing.\r\n\r\nCan only be used on Pick-up Pets.', '1', '2', NULL, 'E', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('86', '26855', 'Bead Slot Key', 'Use this key to unlock a Bead Slot in your Buff Pet. The key is consumed when used. ', '1', '2', NULL, 'P', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('87', '26910', 'Pick-Up Pet Upgrade', 'This powerful magic spell tranforms your normal Pick-up Pet into a Special Buff Pet. You must have your Pick-up summoned when attempting to use this spell. ', '1', '8', NULL, 'P', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('88', '21081', 'Little Lykan', 'A little Lykan that follows its master around and picks up dropped items.\r\nThis pet also has the ability to buff its owner.', '1', '20', NULL, 'O', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('89', '26854', 'Tiny Tanuki', 'Tiny Tanuki follows his master around and picks up dropped items.\r\nThis pet also has the ability to buff its owner.', '1', '20', NULL, 'O', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('90', '21000', 'Baby Lawolf', 'This Baby Lawolf Pet follows his owner around and picks up dropped items! A Flyffers best friend!', '1', '16', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('91', '21001', 'Baby Aibatt', 'This Baby Aibatt Pet follows his owner around and picks up dropped items!', '1', '16', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('92', '21002', 'Baby Leyena', 'This Baby Leyena Pet follows his owner around and picks up dropped items!', '1', '18', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('93', '21003', 'Baby Luia', 'This Baby Luia Pet follows his owner around and picks up dropped items!', '1', '18', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('94', '21004', 'Doggy', 'Cute doggy which follows its master and pick up the dropped items.', '1', '16', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('95', '21005', 'Kitty', 'Cute kitty that follows its master and picks up dropped items.', '1', '16', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('96', '21006', 'Soccerball Angel', 'This Soccerball Angel follows his owner around and picks up dropped items!', '1', '18', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('97', '21026', 'Baby Penguin', 'This Baby Penguin Pet follows his owner around and picks up dropped items!', '1', '18', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('98', '21028', 'Baby Cobra', 'This Baby Cobra Pet follows his owner around and picks up dropped items!', '1', '16', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('99', '21065', 'Little Mia', 'This lost Little Mia follows her owner around and picks up dropped items. Dont worry about her running away, she comes with a ball and chain.', '1', '18', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('100', '21086', 'Cheshire Cat', 'A cute, Cheshire Cat that follows its master around and picks up dropped items. ', '1', '18', NULL, 'N', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('101', '26681', 'Coral Island Ticket (1 day)', 'This tropical ticket allows you to access Coral Island for 1 Day. There, youll find level 43 - 64 monsters that great additional EXP points as well as increased loot drops. This ticket lasts for 24 hours (whether you''re logged in or not). ', '1', '1', NULL, 'M', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('102', '26682', 'Coral Island Ticket (15 days)', 'This tropical ticket allows you to access Coral Island for 15 Days. There, youll find level 43 - 64 monsters that great additional EXP points as well as increased loot drops. This ticket lasts for 15 Days (whether you''re logged in or not). ', '1', '5', NULL, 'M', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('103', '26558', 'Azria Ticket (1 day)', 'You dont need to buy any chocolate bars to get into Azria, just buy this Azria Ticket (1-day) and youre in! Expires 24 hours after activation.', '1', '1', NULL, 'M', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('104', '26529', 'Azria Ticket (7 days)', 'A Golden Ticket that grants the user entry into a hidden land filled with some of the most powerful monsters in Madrigal. Lasts for 7 Days after activation.', '1', '4', NULL, 'M', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('105', '26530', 'Azria Ticket (15 days)', 'A Golden Ticket that grants the user entry into a hidden land filled with some of the most powerful monsters in Madrigal. Lasts for 15 Days after activation.', '1', '6', NULL, 'M', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('106', '10463', 'Scroll of G-Name Change', 'This scroll allows the user to change the name of the Guild. Warning: Guild Leadership required!', '1', '10', NULL, 'L', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('107', '10428', 'Scroll of Selected Party', 'When used, the users party will obtain the ability to change into an advanced party instantly. (Level party up to 10)', '1', '1', NULL, 'L', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('108', '26537', 'Scroll of Party EXP (7 days)', 'Increase the rate at which Party EXP is gained by 50%, when the party leader has it activated. Lasts 7 days from activation. Note that duration expires even when logged off. ', '1', '2', NULL, 'L', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('109', '26538', 'Scroll of Party EXP (15 days)', 'Increase the rate at which Party EXP is gained by 50%, when the party leader has it activated. Lasts 15 days from activation. Note that duration expires even when logged off. ', '1', '3', NULL, 'L', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('110', '26539', 'Scroll of Party Skill (7 days)', 'Allows Party Skills to be stacked, combining their duration, but not effect. Works when the party leader has it activated. Lasts 7 days from activation. Note that duration expires even when logged off. ', '1', '1', NULL, 'L', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('111', '26540', 'Scroll of Party Skill (15 days)', 'Allows Party Skills to be stacked, combining their duration, but not effect. Works when the party leader has it activated. Lasts 15 days from activation. Note that duration expires even when logged off. ', '1', '2', NULL, 'L', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('112', '20169', 'Guild House Return Scroll', 'The Guild House Return Scroll takes you back to your Guild House from anywhere in Madrigal. Need to get somewhere fast? Well this handy tool will get you back to your Guild House Teleporter in a snap!', '10', '1', NULL, 'L', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('113', '10217', 'Common Bank 30', 'Use of this item allows a player to access the bank of all characters on that account within that cluster for 30 Days.', '1', '6', NULL, 'K', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('114', '10216', 'Common Bank 15', 'Use of this item allows a player to access the bank of all characters on that account within that cluster for 15 Days.', '1', '4', NULL, 'K', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('115', '15083', 'Scroll of Private Custody', 'Allows you to instantly access your bank (1 time use). Comes with 10 units.', '10', '2', NULL, 'K', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('116', '26477', 'Extra Bag (30 days)', 'Increases inventory slots in Backpack. (Press B to open your Backpack.) Expires in 30 Days after activation.', '1', '2', NULL, 'K', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('117', '10220', 'Transy', 'Use this item to change your characterss gender. ', '1', '10', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('118', '10426', 'Scroll of Holy', 'Removes all harmful ailments from character (Excluding Karma). Comes with 10 units.', '10', '2', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('119', '10430', 'Scroll of Blessing', 'Will prevent experience (EXP) loss upon death when used. Must be activated before death. Will last up until the point of death. Comes with 10 units.', '10', '2', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('120', '10431', 'Scroll of Resurrection', 'Upon death no experience is lost and the character is revived at the location of death. Comes with 10 units.', '10', '4', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('121', '10212', 'Full Shout 15', 'Enables the user to shout across the entire channel for 15 days. Minimum level: 20', '1', '3', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('122', '10213', 'Full Shout 30', 'Enables the user to shout across the entire channel for 30 days. Minimum level: 20', '1', '5', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('123', '10434', 'Re-Skill', 'A Re-Skill allows a character to reset all of their Skill Points so that they can be reallocated to different stats.\r\n\r\nIf you want to see where your current Skill Points are spent, open your Skills Menu (K Key).', '1', '10', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('124', '10211', 'Re-Stat', 'Resets all your stat values back to 15, allowing you to redistribute your stat points. NOTE: This can not be used until after level 15 and the completion of the first job change.', '1', '10', NULL, 'J', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('125', '2898', 'Fresh Ddukguk', '<b>Name:</b> Fresh Ddukguk\r\n<b>Item Type:</b> Recovery\r\n<b>Info:</b> Consuming this food instantly restores 9,999 FP.\r\n<b>Stat Effected:</b> Focus Points\r\n<b>Recovery Rate:</b> 9,999 FP\r\n<b>Max Recovery:</b> 20,000 FP\r\n<b>Duration:</b> Instant\r\n<b>Sell Price:</b> 125 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '1', NULL, 'I', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('126', '2899', 'Sweet Ddukguk', '<b>Name:</b> Sweet Ddukguk\r\n<b>Item Type:</b> Recovery\r\n<b>Info:</b> Consuming this food instantly restores 9,999 MP.\r\n<b>Stat Effected:</b> Magic Points\r\n<b>Recovery Rate:</b> 9,999 MP\r\n<b>Max Recovery:</b> 20,000 MP\r\n<b>Duration:</b> Instant\r\n<b>Sell Price:</b> 125 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '1', NULL, 'I', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('127', '2897', 'Hot Ddukguk', '<b>Name:</b> Hot Ddukguk\r\n<b>Item Type:</b> Recovery\r\n<b>Info:</b> Consuming this food instantly restores 9,999 HP.\r\n<b>Stat Effected:</b> Health Points\r\n<b>Recovery Rate:</b> 9,999 HP\r\n<b>Max Recovery:</b> 20,000 HP\r\n<b>Duration:</b> Instant\r\n<b>Sell Price:</b> 125 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '1', NULL, 'I', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('128', '10206', 'Remantis Laccotte', '<b>Name:</b>  Remantis Laccotte\r\n<b>Item Type:</b> Recovery\r\n<b>Info:</b> A favorite of fine food connoisseurs throughout Madrigal, this delectable dish completely restores your Health Points (HP). Delicious!!\r\n<b>Stat Effected:</b> Health Points\r\n<b>Recovery Rate:</b> 999,999,999 HP\r\n<b>Max Recovery:</b> None\r\n<b>Cooldown Time:</b> None\r\n<b>Duration:</b> Instant\r\n<b>Sell Price:</b> 0 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '2', NULL, 'I', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('129', '26232', 'Elixir of Evasion', 'Increases your Parry Rate by 5%. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('130', '26224', 'Elixir of the Tiger', 'Increases your Strength (STR) by +7. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('131', '26225', 'Elixir of the Rabbit', 'Increases your Dexterity (DEX) by +7. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('132', '26226', 'Elixir of the Fox', 'Increases your Intellect (INT) by +7. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('133', '26227', 'Elixir of the Lion', 'Increases your Stamina (STA) by +7. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('134', '26228', 'Elixir of Stone', 'Increases your Defense (DEF) by +70. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('135', '26220', 'Potion of Recklessness', 'Increases your Critical Hit Rate by 5%. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('136', '26221', 'Potion of Swiftness', 'Increases your Attack Speed by 5%. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('137', '26222', 'Potion of Accuracy', 'Increases your Hit Rate by 5%. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('138', '26223', 'Potion of Clarity', 'Decreases your Casting Time by 5%. Lasts 30 minutes.', '10', '2', NULL, 'H', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('139', '26812', 'Power Scroll', 'Increases your Health Points (HP) and Attack Power (ATK) for one hour. Once it wears off, the scroll is returned to your inventory as a scroll of the next level up! Thats 3 hours of buffs!\r\n<b>1st Scroll:</b> Power Scroll - HP +150 ATK +100\r\n<b>2nd Scroll:</b> Charged Power Scroll - HP +300 ATK +200\r\n<b>3rd Scroll:</b> Super Charged Power Scroll - HP +450 ATK +300\r\n\r\n<b>Please Note:</b> After using the first scroll, subsequent scrolls will be non-tradable.', '5', '3', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('140', '10209', 'Bull Hamstern', '<b>Name:</b> Bull Hamstern\r\n<b>Item Type:</b> Enhancer\r\n<b>Info:</b> Increases your maximum health (HP) by 300 for 15 minutes.\r\n<b>Stat Effected:</b> Health\r\n<b>Duration:</b> 15 minutes\r\n<b>Sell Price:</b> 0 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '1', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('141', '10210', 'Grilled Eel', '<b>Name:</b> Grilled Eel\r\n<b>Item Type:</b> Enhancer\r\n<b>Info:</b> Increases your maximum health (HP) by 50% for 15 minutes.\r\n<b>Stat Effected:</b> Health\r\n<b>Duration:</b> 15 minutes\r\n<b>Sell Price:</b> 0 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '3', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('142', '10208', 'Vital Drink X', '<b>Name:</b> Vital Drink X\r\n<b>Item Type:</b> Enhancer\r\n<b>Info:</b> Grants the imbiber unlimited FP for 20 minutes.\r\n<b>Stat Effected:</b> Focus Points\r\n<b>Duration:</b> 20 minutes\r\n<b>Sell Price:</b> 0 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '2', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('143', '10207', 'Refresher Hold', '<b>Name:</b> Refresher Hold\r\n<b>Item Type:</b> Enhancer\r\n<b>Info:</b> Grants the imbiber unlimited MP for 20 minutes.\r\n<b>Stat Effected:</b> Magic Points\r\n<b>Duration:</b> 20 minutes\r\n<b>Sell Price:</b> 0 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '2', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('144', '10270', 'Upcut Stone', '<b>Name:</b> Upcut Stone\r\n<b>Item Type:</b> Enhancer\r\n<b>Info:</b> Increases your Attack Power (ATK) by 20% for 20 minutes.\r\n<b>Stat Effected:</b> Attack Power\r\n<b>Duration:</b> 20 minutes\r\n<b>Sell Price:</b> 0 penya\r\n<b>Maximum Stack Size:</b> 9999', '10', '3', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('145', '10218', 'Activition', 'Allows the Action Slot to be used without a delay for 10 min. NOTE: This ONLY removes the Action Slot delay, not the timer for Boards/Brooms, food, blinkwings, etc. Comes with 10 units.', '10', '2', NULL, 'G', '0', '.jpg', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('146', '30115', 'Scroll of Acquisition (Low)', 'Increases the drop rate of a Masquerpet or Gift Box by a small percentage.', '1', '1', NULL, 'G', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('147', '30148', 'Scroll of Amplification ES (S)', 'For all levels\r\nUse 1: Exp. Point x 1.5 for 1 hour.\r\nStacks up to 3 times for Exp. Point x 2.5 for 1 hour.\r\n\r\nNOTE: Exp. Points gained from quests are excluded.', '3', '5', NULL, 'G', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('148', '26218', 'Item Transy (B)', 'This item allows you to change the gender requirement on armor pieces. The Item Transy B works on armor between level 61 and level 120.', '1', '4', NULL, 'F', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('149', '26204', 'Item Transy (A)', 'This item allows you to change the gender requirement on armor pieces. The Item Transy B works on armor between level 1 and level 60.', '1', '2', NULL, 'F', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('150', '26458', 'Scroll of Reduction B', 'Reduces the required level to use an item by 5. (Once changed, it cannot be traded, dropped, or placed in a bank.)', '1', '3', NULL, 'F', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('151', '26459', 'Scroll of Reduction A', 'Reduces the required level to use an item by 10. (Once changed, it cannot be traded, dropped, or placed in a bank.)', '1', '5', NULL, 'F', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('152', '20037', 'Scroll of Element Change', 'A mysterious scroll that allows the owner to change the type of element on an item without losing the upgrade amount.', '1', '3', NULL, 'F', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('153', '26462', 'Scroll of Reversion', 'Reverts an awakened item to its original form.', '1', '1', NULL, 'E', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('154', '10489', 'Scroll of Smelting (Elements)', 'This scroll increases your elemental upgrade chance by 10%. Effective up to +10. Comes with 5 units.', '10', '1', NULL, 'D', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('155', '10468', 'Scroll of Smelting', 'Increases upgrade chance by 10% up to +7. One Time Use (One scroll is needed per upgrade attempt). Comes with 5 units.', '10', '3', NULL, 'D', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('156', '26473', 'Scroll of AProtect', 'Protects Jewelry from being destroyed when an upgrade fails. Comes with 5 units.', '10', '4', NULL, 'D', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('157', '10488', 'Scroll of XProtect', 'Scroll which protects a Unique weapon from destruction while upgrading it into an Ultimate weapon. Comes with 5 units.', '10', '6', NULL, 'D', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('158', '10465', 'Scroll of GProtect', 'When failing an item pierce, the armor is protected from breaking. One time use. Comes with 5 units.', '10', '5', NULL, 'D', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('159', '10464', 'Scroll of SProtect', 'When failing an upgrade, the item is protected from breaking. Comes with 5 units.', '10', '4', NULL, 'D', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('160', '26463', 'Blessing of the Goddess', 'Adds an additional stat to Premium Shop fashion items and cloaks.  Target item becomes no-trade unless the blessing is removed by Jewel Manager Peach in Flarine.', '1', '2', NULL, 'E', '0', '.gif', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('161', '30302', 'Raffle Box B', 'If you purchase this box, the lowest value item you will receive is an Azria Ticket (7 Days), but you have the potential to get something of greater value instead. That means, the default item you receive will be an Azria Ticket (7 Days). However, instead of the Azria Ticket (7 Days), you may receive something of higher value.\r\n\r\nThis Box can contain one of the following items: Clock Bike(White)\r\nMeteo Bike(Green)\r\nSyila Hoverbike\r\nGold Battery\r\nExtra Bag\r\nFull Shout 30\r\nSilver Battery\r\nAzria Ticket (7 days)\r\nScroll of Reduction A\r\nAzria Ticket (15 days)\r\nScroll of Reduction B', '1', '4', NULL, 'B', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('162', '30301', 'Raffle Box A', 'If you purchase a box, the lowest value item you will receive is a Scroll of Amplification, but you have the potential to get something of greater value. That means, the default item you receive will be a Scroll of Amplification. However, instead of the Scroll of Amplification, you may receive something of higher value.\r\n\r\nThis Box can contain one of the following items:\r\n\r\nBaby Rabbit\r\nBaby Cobra\r\nBaby Monkey\r\nBaby Pig\r\nBaby Beagle\r\nLittle Maid Cardpuppet\r\nFeed Bag (6 hrs)\r\nBlessing of the Pet Tamer\r\nScroll of Reduction B\r\nScroll of Reduction A\r\nScroll of Acquisition (Low)\r\nScroll of Amplification ES (S)', '1', '2', NULL, 'B', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('163', '30305', 'Lottery Box', 'If you purchase a box, the lowest value item you will receive is ten Remantis Laccotte, but you have the potential to get something of greater value. That means, the default item you receive will be a Scroll of Amplification. However, instead of the Remantis Laccotte, you may receive something of higher value.\r\n\r\nThis Box can contain one of the following items:\r\n\r\nPet Cow\r\nFool Glasses\r\nScroll of Amplification ES (S) x2\r\nAzria Ticket (7 days)\r\nUpcut Stone x5\r\nScroll of Resurrection x5\r\nRemantis Laccotte x10', '1', '2', NULL, 'B', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('164', '20224', 'Adept''s Precious Bead Box', 'This box has a chance to contain ONE of the following Pet Beads at random:\r\n\r\nPrecious Bead of the Rabbit (1)\r\nPrecious Bead of the Fox (1)\r\nPrecious Bead of the Lion (1)\r\nPrecious Bead of Relentless Power (1)\r\nPrecious Bead of Clarity (1)\r\nPrecious Bead of Focused Power (1)\r\nPrecious Bead of the Steadfast Defender (1)\r\nPrecious Bead of the Ardent Defender (1)\r\nPrecious Bead of the Winds (1)\r\nPrecious Bead of Swiftness (1)\r\nPrecious Bead of Power (1)\r\nPrecious Bead of the Protector (1)\r\nPrecious Bead of the Sorceror (1)\r\nPrecious Bead of Evasion (1)\r\nPrecious Bead of Fortitude (1)\r\nPrecious Bead of Malice (1) ', '1', '1', NULL, 'B', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('165', '20223', 'Champion''s Precious Bead Box', 'This box has a chance to contain ONE of the following Pet Beads at random:\r\n\r\nPrecious Bead of the Tiger (1)\r\nPrecious Bead of the Rabbit (1)\r\nPrecious Bead of the Lion (1)\r\nPrecious Bead of Relentless Power (1)\r\nPrecious Bead of the Steadfast Defender (1)\r\nPrecious Bead of Recklessness (1)\r\nPrecious Bead of Profuse Bleeding (1)\r\nPrecious Bead of the Winds (1)\r\nPrecious Bead of Accuracy (1)\r\nPrecious Bead of Swiftness (1)\r\nPrecious Bead of Power (1)\r\nPrecious Bead of the Protector (1)\r\nPrecious Bead of Evasion (1)\r\nPrecious Bead of Fortitude (1)\r\nPrecious Bead of Soul Reaving (1)\r\nPrecious Bead of Malice (1)', '1', '1', NULL, 'B', '0', '.png', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('166', '26681', 'Coral Island Ticket (1 day) Bundle (6)', 'This bundle has 6x 1 Day Coral Island Tickets for less than the cost of buying them individually.\r\n\r\nEach tropical ticket allows you to access Coral Island for 1 Day. There, you''ll find level 43 - 64 monsters that great additional EXP points as well as increased loot drops. This ticket lasts for 24 hours (whether youre logged in or not).', '6', '4', NULL, 'A', '0', '.jpg', '1', '1', '26681', 'Coral Island Ticket (1 day)', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('167', '26558', 'Azria Ticket (1 day) Bundle (6)', 'This bundle has 6x 1 Day Azria Tickets for less than the cost of buying them individually.\r\n\r\nEach snowy ticket allows you to access Azria for 1 Day. There, you''ll find level 73 - 115 monsters that great additional EXP points as well as increased loot drops. This ticket lasts for 24 hours (whether youre logged in or not).', '6', '5', NULL, 'A', '0', '.gif', '1', '1', '26558', 'Azria Ticket (1 day)', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('168', '30148', 'Amplifications (10) + Power Scrolls (2)', 'This Amplification Bundle comes with 10 Scrolls of Amplification + 2 FREE Power Scrolls. That a total of 20% OFF.\r\n\r\nAmplification Scrolls work by increasing your EXP gain from killing monsters by x1.5. You can stack 3 Scrolls of Amplification together to receive x2.5 EXP!\r\n\r\nEach Scroll lasts 1 hour.', '12', '25', '20', 'A', '0', '.png', '1', '1', '30148', 'Scroll of Amplification ES (S)', '10', '26812', 'Power Scroll', '2', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('169', '26462', 'Reversion (50) + Raffle Box B (2)', 'This bundle comes with 50x Scroll or Reversion at 15% OFF and 2 FREE Raffle Box B!', '52', '50', '35', 'A', '0', '.png', '1', '1', '26462', 'Scroll of Reversion', '50', '30302', 'Raffle Box B', '2', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO [PREMIUM_SHOP_TBL] VALUES ('170', '10464', 'Scroll of SProtect (40)', 'The SProtect Bundle (40) comes with 40 Scrolls of SProtect and a 10% discount.', '40', '16', '15', 'A', '0', '.png', '1', '1', '10464', 'Scroll of SProtect', '20', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


/****** Object:  StoredProcedure [dbo].[shopMessengerList]    Script Date: 04/30/2010 23:20:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
-- =============================================
-- Author:		<Treachery>
-- Create date: <4/30/2010>
-- Description:	<Returns with the players in the selected player's messenger.>
-- =============================================
CREATE  Procedure [dbo].[shopMessengerList]
		@pserverindex		char(2),
		@pPlayerID			char(7)
AS
SET NOCOUNT ON

	SELECT	a.idFriend, b.m_szName
	FROM	dbo.tblMessenger a
			INNER JOIN dbo.CHARACTER_TBL b
				ON (a.serverindex=b.serverindex AND a.idFriend=b.m_idPlayer)
	WHERE	a.serverindex=@pserverindex
		AND	a.idPlayer=@pPlayerID
		AND	a.chUse='T'
		AND	b.isblock='F'
	ORDER BY	b.CreateTime
	
	RETURN

SET NOCOUNT OFF

/****** Object:  StoredProcedure [dbo].[shopSendItem]    Script Date: 04/30/2010 23:19:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Treachery>
-- Create date: <4/30/2010>
-- Description:	<Send an item to a player.>
-- =============================================
CREATE PROCEDURE [dbo].[shopSendItem]
	-- Add the parameters for the stored procedure here
	@m_idPlayer			char(7),
	@serverindex		char(2),
	@item_name			text,
	@item_count			int,
	@item_id			int,
	@m_idSender			char(7) = '0000000'
AS
BEGIN
	SET NOCOUNT ON;
						INSERT ITEM_SEND_TBL
							(
								m_idPlayer,serverindex,Item_Name,Item_count,idSender,adwItemId0
							)
						VALUES
							(
								@m_idPlayer,@serverindex,@item_name,@item_count,@m_idSender,@item_id
							)
	RETURN 1
END